### ISSUE TITLE
I can't find the adder.aig

### ISSUE THREAD

**Issue by shetor** [OSCC-Project/iMap#1]
ERROR: read the aig file FAIL, path from: ../../../benchmark/EPFL/arithmetic/adder.aig
I wanted to test the adder.aig ,but according to the Readme ,I didn't find the aig file.What are the possible problems

**Comment by nlwmode** [comment]
You can download the AIG file from the following repo: "https://gitee.com/nlwmode_personal/benchmark"

**Comment by nlwmode** [comment]
You can download the AIG file from the following repo: "https://gitee.com/nlwmode_personal/benchmark"
